#!name=交管12123
#!desc=【交管12123】Token/Cookie 自动抓取，支持组件服务（Surge 原生 / Quantumult-X 需配合资源解析器）。\n使用方法：打开交管12123「支付宝小程序」并登录，即可自动抓取 Token。资源解析器：https://t.me/QuanXNews/110
#!category=组件服务

[Script]
# 模块分类 · 交管组件服务参数获取
交管12123·参数获取 = type=http-request,pattern=^https:\/\/miniappcsfw\.122\.gov\.cn:8443\/openapi\/invokeApi\/business\/biz,requires-body=1,max-size=0,timeout=1000,script-path=https://raw.githubusercontent.com/Nanako718/Scripting/main/Quantumult%20X/js/12123_token.js,script-update-interval=0

[MITM]
hostname = %APPEND% miniappcsfw.122.gov.cn:8443
