#!name=网上国网组件服务
#!category=组件服务
#!desc=95598（通过账号密码登录聚合电费/电量/阶梯数据，供组件使用）
#!author=ByteValley
#!version=2025-12-12R1

[Script]
# 模块分类 · 网上国网（95598）数据接口
网上国网·数据接口 = type=http-request,pattern=^https?:\/\/api\.wsgw-rewrite\.com\/electricity\/bill\/all,requires-body=1,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Component/wsgw_index.js,script-update-interval=0

[MITM]
hostname = %APPEND% api.wsgw-rewrite.com