#!name =网上国网组件服务
#!category=组件服务
#!desc=95598 

[Script]
网上国网·获取 OpenID = type=http-request,pattern=^https?:\/\/osg-open\.sgcc\.com\.cn\/osg-open-p0001\/member\/c5\/f05,requires-body=0,max-size=0,timeout=1000,script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/95598/95598.weapp.js,script-update-interval=0
网上国网·电费查询 = type=cron,cronexp=5 21 * * *,wake-system=1,script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/95598/95598.weapp.js,timeout=60
[MITM]
hostname = %APPEND% osg-open.sgcc.com.cn
