[mitm]
hostname = wx.10099.com.cn

[rewrite_local]
^https:\/\/wx\.10099\.com\.cn\/contact-web\/api\/busi\/qryUserInfo url script-request-body https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Component/ChinaBroadnet.js
