#!name=中国移动组件服务
#!desc= 查询套餐内通话、套餐使用情况
#!category=组件服务
#!author= ByteValley
#!arguments=禁用获参重写:''
#!arguments-desc=[参数设置]\n\n⓵ 禁用脚本：填写#禁用捕获参数重写。

[Script]
{{{禁用获参重写}}}移动参数获取 = type = http-request, pattern=^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/[LD]N\/(uam(onekey|randcode)login|realPersonAuthentication)\/autoLogin,requires-body=1,max-size=0,script-path=https://github.com/ChinaTelecomOperators/ChinaMobile/releases/download/Prerelease-Alpha/10086.js

移动余量查询·组件 = type = http-request, pattern=^https?:\/\/api\.example\.com\/10086\/query, script-path=https://github.com/ChinaTelecomOperators/ChinaMobile/releases/download/Prerelease-Alpha/10086.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% api.example.com, client.app.coc.10086.cn
