#!name=订阅信息
#!desc=机场订阅信息展示,流量使用及剩余信息与到期日期
#!author=ByteValley
#!category=功能看板
#!arguments=Update:21600,DefaultIcon:cellularbars,DefaultIconColor:#1E90FF,Title1:'机场名称',URL1:'订阅链接',ResetDay1:'重置日期',Title2:'机场名称',URL2:'订阅链接',ResetDay2:'重置日期',Title3:'机场名称',URL3:'订阅链接',ResetDay3:'重置日期',Title4:'机场名称',URL4:'订阅链接',ResetDay4:'重置日期',Title5:'机场名称',URL5:'订阅链接',ResetDay5:'重置日期',Title6:'机场名称',URL6:'订阅链接',ResetDay6:'重置日期',Title7:'机场名称',URL7:'订阅链接',ResetDay7:'重置日期',Title8:'机场名称',URL8:'订阅链接',ResetDay8:'重置日期',Title9:'机场名称',URL9:'订阅链接',ResetDay9:'重置日期',Title10:'机场名称',URL10:'订阅链接',ResetDay10:'重置日期'
#!arguments-desc=Update=刷新间隔(秒);TitleN=机场名称;URLN=订阅链接;ResetDayN=重置日期(1~31或中文提示);DefaultIcon=SF Symbols 名称;DefaultIconColor=十六进制色值

[Panel]
订阅查询=script-name=机场订阅查询,update-interval={{{Update}}}

[Script]
机场订阅查询=type=generic,timeout=15,script-path=https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Panel/subscribe_info.js,argument=defaultIcon={{{DefaultIcon}}}&defaultIconColor={{{DefaultIconColor}}}&title1={{{Title1}}}&url1={{{URL1}}}&resetDay1={{{ResetDay1}}}&title2={{{Title2}}}&url2={{{URL2}}}&resetDay2={{{ResetDay2}}}&title3={{{Title3}}}&url3={{{URL3}}}&resetDay3={{{ResetDay3}}}&title4={{{Title4}}}&url4={{{URL4}}}&resetDay4={{{ResetDay4}}}&title5={{{Title5}}}&url5={{{URL5}}}&resetDay5={{{ResetDay5}}}&title6={{{Title6}}}&url6={{{URL6}}}&resetDay6={{{ResetDay6}}}&title7={{{Title7}}}&url7={{{URL7}}}&resetDay7={{{ResetDay7}}}&title8={{{Title8}}}&url8={{{URL8}}}&resetDay8={{{ResetDay8}}}&title9={{{Title9}}}&url9={{{URL9}}}&resetDay9={{{ResetDay9}}}&title10={{{Title10}}}&url10={{{URL10}}}&resetDay10={{{ResetDay10}}}