#!name=鲍鱼盒子
#!desc=鲍鱼盒子增强，解锁会员功能
#!category=功能增强
#!author=ByteValley
#!version=2026-05-20R1
#!arguments=token:bearer 47516c8088984f2c4f1788be51216289

[Map Local]
# 鲍鱼盒子 - 屏蔽上报逻辑
^https?://siajksslwiso\.anningsh\.com/report data-type=text data=" " status-code=200

[Script]
# 鲍鱼盒子 - 注入会员逻辑
鲍鱼盒子 = type=http-request, pattern=^https?:\/\/.*\/api\/(video\/report_item|live\/room\/detail|video\/related|video\/detail|socialposts_info|my\/profile), script-path=https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Enhancement/abaloneBox_injector.js, argument=token={{{token}}}, requires-body=false, timeout=60

[MITM]
# 鲍鱼盒子 - 解密域名
hostname = %APPEND% 211.154.21.150, w1c2.ooat88.com, tu.dfgfdg.win, 103.44.236.*, *.artrg.cn, vkfqb.ojyrz.com, byapi.*.com, 211.99.98.*, 103.39.222.*, yubaoyu.oss-cn-shenzhen.aliyuncs.com, *api.h8h4h.com, 42.157.129.25, siajksslwiso.anningsh.com, 211.99.98.63, 111.180.204.11, 88.gbvdfe.com, vdop.fqoas.com, ica.ooat88.com, 103.44.236.131:8001
