#!name=鲍鱼盒子
#!desc=自动注入最新 Authorization 和 URL 签名参数 (2026-02-28)
#!author=ByteValley
#!category=功能增强
#!date=2026-02-28

[Rule]
# 强制让 IP 请求走解密，防止由于不走代理导致的拦截失败
IP-CIDR, 211.154.21.150/32, DIRECT

[Script]
# 拦截个人资料、视频详情等关键接口，修改请求头和URL参数
鲍鱼盒子修复 = type=http-request, pattern=^https?:\/\/.*\/api\/(video\/report_item|live\/room\/detail|video\/related|video\/detail|socialposts_info|my\/profile), script-path=https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Enhancement/byhz_header_fix.js, requires-body=false

[MITM]
hostname = %APPEND% 211.154.21.150:8020, w1c2.ooat88.com, *api.h8h4h.com, byapi.*.com
