#!name=乌贼
#!desc=乌贼增强，自用请求头与加密请求体成套替换
#!category=功能增强
#!author=ByteValley
#!version=2026-05-20R2

[Script]
# 请求替换 - 乌贼主接口
乌贼 = type=http-request, pattern=^https?:\/\/s30s\.booking\.gxggzx\.com\/APl\/(Live|App|User)\/, script-path=https://raw.githubusercontent.com/ByteValley/NetTool/main/Scripts/Enhancement/squid_injector.js, requires-body=true, timeout=60

[MITM]
# 主接口域名
hostname = %APPEND% s30s.booking.gxggzx.com
