name: 网络测速
description: 落地信息 + 网络测速

author: ByteValley
homepage: https://github.com/ByteValley/NetTool
dns: {}

scriptings:
  - generic:
      name: 网络测速·组件
      script_url: https://raw.githubusercontent.com/ByteValley/NetTool/main/Beta/Scripts/Widget/network_info_ctx.js
      env:
        _compat.$argument: Update={{{Update}}}&Timeout={{{Timeout}}}&BUDGET={{{BUDGET}}}&MASK_IP={{{MASK_IP}}}&MASK_POS={{{MASK_POS}}}&IPv6={{{IPv6}}}&DOMESTIC_IPv4={{{DOMESTIC_IPv4}}}&DOMESTIC_IPv6={{{DOMESTIC_IPv6}}}&LANDING_IPv4={{{LANDING_IPv4}}}&LANDING_IPv6={{{LANDING_IPv6}}}&TW_FLAG_MODE={{{TW_FLAG_MODE}}}&IconPreset={{{IconPreset}}}&Icon={{{Icon}}}&IconColor={{{IconColor}}}&SUBTITLE_STYLE={{{SUBTITLE_STYLE}}}&SUBTITLE_MINIMAL={{{SUBTITLE_MINIMAL}}}&GAP_LINES={{{GAP_LINES}}}&SD_STYLE={{{SD_STYLE}}}&SD_LANG={{{SD_LANG}}}&SD_TIMEOUT={{{SD_TIMEOUT}}}&SD_CONCURRENCY={{{SD_CONCURRENCY}}}&SD_REGION_MODE={{{SD_REGION_MODE}}}&SD_ICON_THEME={{{SD_ICON_THEME}}}&SD_ARROW={{{SD_ARROW}}}&SD_SHOW_LAT={{{SD_SHOW_LAT}}}&SD_SHOW_HTTP={{{SD_SHOW_HTTP}}}&SERVICES={{{SERVICES}}}&LOG={{{LOG}}}&LOG_LEVEL={{{LOG_LEVEL}}}&LOG_TO_PANEL={{{LOG_TO_PANEL}}}&LOG_PUSH={{{LOG_PUSH}}}&PROXY_POLICY={{{PROXY_POLICY}}}
      update_interval: 21600
      timeout: 14


widgets:
  - name: 网络测速
    script_name: 网络测速·组件
